### ISSUE TITLE
macos monterey stuck at 13 minutes remaining

### ISSUE THREAD

**Issue by ubuntupunk** [wimpysworld/quickemu#228] opened 2021-11-15 10:05 UTC
#### Expected behaviour

macos installs as per instructions

#### Actual behaviour

gets stuck at 13 minutes remaining. Still like this 8 hours later.

#### Steps to reproduce the behaviour

quickemu --vm monterey.conf
erase disk
reinstall monterey

#### Quickemu output

quickemu

Usage
```  
quickemu --vm ubuntu.conf

You can also pass optional parameters
  --delete                : Delete the disk image.
  --display               : Select display backend. 'sdl' (default), 'gtk', 'none', or 'spice'
  --fullscreen            : Starts VM in full screen mode (Ctl+Alt+f to exit)
  --ignore-msrs-always    : Configure KVM to always ignore unhandled machine-specific registers
  --screen <screen>       : Use specified screen to determine the window size.
  --shortcut              : Create a desktop shortcut
  --snapshot apply <tag>  : Apply/restore a snapshot.
  --snapshot create <tag> : Create a snapshot.
  --snapshot delete <tag> : Delete a snapshot.
  --snapshot info         : Show disk/snapshot info.
  --status-quo            : Do not commit any changes to disk/snapshot.
  --version               : Print version
```
#### Linux Distribution & Kernel

Run the following and paste the output.

```bash
lsb_release --all
LSB Version:	core-11.1.0ubuntu2-noarch:printing-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal

uname -a
Linux afropunk 5.11.0-40-generic #44~20.04.2-Ubuntu SMP Tue Oct 26 18:07:44 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by ubuntupunk** [comment] 2021-11-16 04:18
Problem solved. Steps to fix:

htop
F3 quickemu
kill
restart quickemu

Quickemu periodically dies or freezes. Solution, reboot VM, continue setup.

**Comment by flexiondotorg** [comment] 2021-11-17 18:20
This is not a bug in Quickemu, so I am closing this but invite you to join our Discord if you have questions about the macOS install process 🙂

  * https://wimpysworld.io/discord

**Closed by flexiondotorg** 2021-11-17 18:20 UTC
